### PR TITLE
Added a CLI, 100% tested and works.

### PR DESCRIPTION
**Pull request by Haider-Ali-Dev**
# Description

Added a cli written in Rust using clap, it works, when running `reddit-video-maker create`, it simply underneath the hood runs 
`python main.py`.
# Issue Fixes

NONE

None

# Checklist:

- [X] I am pushing changes to the **develop** branch
- [X] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [X] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [X] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

### CODE REVIEW

**Comment by CallumIO** [comment]
Don't get me wrong - I love Rust and am all for RIIR. But, why?

We have people who don't even have python installed trying to run the bot - trying to get them to install rust as well would make it even more difficult.

Sticking to one language in this case would be a better option.

**Comment by Haider-Ali-Dev** [comment]
Oh cool, my idea was to somehow turn this whole code into a single binary (not the cli) and then distribute binaries, the cli would come with all python code so no worries. Nvm my bad, the reason I used Rust is because it’s the best for cli apps and ofc many stuff, I’m also a 100% Rust user, I do know python well. Decided to add bit Rust into the repo.

If you want me to rewrite this in python I’ll do it.

**Comment by micziz** [comment]
I LOOOVE rust, but making a cli in one language and the actual program in another wloud be hard to mantain. Also, rust is way harder to write than python. I suggest you rewrite it in python using click https://click.palletsprojects.com/en/8.1.x/

**Comment by Haider-Ali-Dev** [comment]
@micziz Done. I also added comments, explaining each and every part of the code.

**Comment by micziz** [comment]
Perfect! I think this shloud be merged

**Comment by Haider-Ali-Dev** [comment]
@CallumIO mind taking a look?

**Comment by JasonLovesDoggo** [comment]
I mean I just looked and it really only adds one thing.
-- version
this is kinda useless IMO

**Comment by JasonLovesDoggo** [comment]
Doesn't really add anything useful to the bot

**Comment by Haider-Ali-Dev** [comment]
What do you expect to add when the bot only does one thing? (I’m not being mad)

**Comment by JasonLovesDoggo** [comment]
> What do you expect to add when the bot only does one thing? (I’m not being mad)

I'm saying what's the point of this when it does the exact same functionality as it just not existing?

**Pull request closed without merging**
