### PR TITLE
async WebDriver, async api tts & asyncprew

### PR DESCRIPTION
**Pull request by Drugsosos**
adding async await wherever it's seems good 💯 

TODO:
* async WebDriver
  - [x] move from playwright to pyppeteer
  - [ ] test async WebDriver
  - [x] add/improve typing
  - [ ] fix 'NSFW button remains in title screenshot'
  - [x] update README
  - [x] update install.sh
* asyncprew
  - [ ] create new PR
  - [ ] move prew to asyncprew
  - [ ] add new variable max_comments_to_be_loaded\
  (for the issue with max_video_length, my solution comes with it's own disadvantages)
  - [ ] tests
* other fixes & improvements
  - [ ] create new PR
  - [ ] fix length of downloadable back content
  - [ ] add random back audio/video (maybe)
  - [ ] move Popen('clear'/'cls') to rich.Console.clear
  - [ ] write a factory in utils/voices.py

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
The goal move Popen('clear'/'cls') to rich.Console.clear
Wouldn't work fully because not everything he uses the console

**Comment by tonywiththetommy** [comment]
is it possible with this change that we could censor profanity within the comment screenshots> i.e. editing the text in the web page to say f**k

**Comment by Drugsosos** [comment]
> is it possible with this change that we could censor profanity within the comment screenshots> i.e. editing the text in the web page to say f**k

@tonywiththetommy it was already possible, but we still don't have good enough profane filter, mine only has english list but we want multilingual solution

**Comment by Drugsosos** [comment]
> The goal move Popen('clear'/'cls') to rich.Console.clear
> Wouldn't work fully because not everything he uses the console

@JasonLovesDoggo 
everything is possible ;) 
some refactor needed and everything will be bussin

**Comment by JasonLovesDoggo** [comment]
> > The goal move Popen('clear'/'cls') to rich.Console.clear
> > Wouldn't work fully because not everything he uses the console
> 
> @JasonLovesDoggo 
> everything is possible ;) 
> some refactor needed and everything will be bussin

Lmao But I don't see why this is really necessary.
Also not everything SHOULD be using rich console

**Comment by Drugsosos** [comment]
@JasonLovesDoggo 
'cause it's not the way to use Popen) 
Also it doesn't even work on Unix like systems, I guess (doesn't work on macOS at least)

**Comment by William9923** [comment]
I think this is a really big PR, would be great if it was separated to help the reviewer

**Comment by Drugsosos** [comment]
> I think this is a really big PR, would be great if it was separated to help the reviewer

@William9923 
yeah, i thought about that, I was going to create multiple PRs, but I think it'll be better this way, cause you'll be able to test everything together. 
also I need some common functionally in different places

**Comment by JasonLovesDoggo** [comment]
> > I think this is a really big PR, would be great if it was separated to help the reviewer
> 
> @William9923 
> yeah, i thought about that, I was going to create multiple PRs, but I think it'll be better this way, cause you'll be able to test everything together. 
> also I need some common functionally in different places
> 
> sorry, kinda selfish of myself, but I'll review myself before I'll mark PR as ready to be reviewed and make a list of places I want reviewers to look closer
> 
> edit: no, you actually right, gonna split PR into 4 different PRs later

Oh thank God

**Pull request closed without merging**
