### PR TITLE
Converted spaces into tabs

### PR DESCRIPTION
**Pull request by ART3MISTICAL**
For smaller file sizes and because why not

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Amen

**Review by JasonLovesDoggo — APPROVED** [review]
Lgtm

**Comment by CallumIO** [comment]
Are they converted for all files or just main.py?

**Comment by ART3MISTICAL** [comment]
> Are they converted for all files or just main.py?

just main.py

**Comment by CallumIO** [comment]
> > Are they converted for all files or just main.py?
> 
> just main.py

Could you convert it for all of them, for consistency?

**Comment by ART3MISTICAL** [comment]
> > > Are they converted for all files or just main.py?
> > 
> > 
> > just main.py
> 
> Could you convert it for all of them, for consistency?

ok

**Comment by ART3MISTICAL** [comment]
> > > Are they converted for all files or just main.py?
> > 
> > 
> > just main.py
> 
> Could you convert it for all of them, for consistency?

i have created a fork

**Comment by ART3MISTICAL** [comment]
> > > Are they converted for all files or just main.py?
> > 
> > 
> > just main.py
> 
> Could you convert it for all of them, for consistency?

done

**Comment by JasonLovesDoggo** [comment]
Could you push the changes to this branch

**Comment by ART3MISTICAL** [comment]
> Could you push the changes to this branch

i have created a pull request

**Comment by JasonLovesDoggo** [comment]
Closed for #558

**Pull request closed without merging**
