### PR TITLE
2.4.1

### PR DESCRIPTION
**Pull request by callumio**
Adds a version checker
Adds pyttsx3 to requirements

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Version checker is a nice addition

**Comment by JasonLovesDoggo** [comment]
Version checker is a nice addition

**Comment by StopmotionSimonYT** [comment]
> Version checker is a nice addition

Thank you!

**Comment by JasonLovesDoggo** [comment]
Not the biggest fan about how many duplicated ID regex calls there is but I mean it doesn't impact performance in any substantial ways so approved

**Review by JasonLovesDoggo — APPROVED** [review]

**Pull request merged**
