### PR TITLE
Added TTS reading the text of the post if present

### PR DESCRIPTION
**Pull request by MeDBeD1**
Just a simple change for the bot to be able to read text below the tittle, useful for subreddits like r/maliciouscompliance (WARNING! It doesn't work properly with large posts)

### CODE REVIEW

**Review by CallumIO — CHANGES_REQUESTED** [review]
I think the better way of doing this would be to add it using `content["thread_post"] = submission.selftext`.

Then when getting TTS files, add a new one to read out this text.

**Comment by prasannakarki** [comment]
> I think the better way of doing this would be to add it using `content["thread_post"] = submission.selftext`.
> 
> Then when getting TTS files, add a new one to read out this text.

I tried this already and in some threads the images and voice dont sync. of course my python is a little bit rusty but i cant be that bad right. his way also works as a failsafe. like if the post only has a title and body is null it should still run.

**Comment by CallumIO** [comment]
> > I think the better way of doing this would be to add it using `content["thread_post"] = submission.selftext`.
> > Then when getting TTS files, add a new one to read out this text.
> 
> I tried this already and in some threads the images and voice dont sync. of course my python is a little bit rusty but i cant be that bad right. his way also works as a failsafe. like if the post only has a title and body is null it should still run.

Another approach would still be storing it as a new key, but appending it when requesting voice instead. Then, we still have a clean title string. This would stop it from interfering with #139

**Comment by MeDBeD1** [comment]
> I think the better way of doing this would be to add it using `content["thread_post"] = submission.selftext`.
> 
> Then when getting TTS files, add a new one to read out this text.

Much simpler solution would be to just add text to the title file, because then you do not need to run the exact same pieces of code multiple times. And if there is no text, the returned value will be empty string which does not impact TTS whatsoever, so i believe the original solution would be more efficient

**Comment by CallumIO** [comment]
> > I think the better way of doing this would be to add it using `content["thread_post"] = submission.selftext`.
> 
> > 
> 
> > Then when getting TTS files, add a new one to read out this text.
> 
> 
> 
> Much simpler solution would be to just add text to the title file, because then you do not need to run the exact same pieces of code multiple times. And if there is no text, the returned value will be empty string which does not impact TTS whatsoever, so i believe the original solution would be more efficient (unless i'm missing something)

See my previous reply. I agree it would be simpler but it would also conflict with other parts that may need to use the title. e.g. #139

Additionally it may hit the character limit if we implement the new TTS api in #92

**Comment by MeDBeD1** [comment]
> > > I think the better way of doing this would be to add it using `content["thread_post"] = submission.selftext`.
> > 
> > 
> > > 
> > 
> > 
> > > Then when getting TTS files, add a new one to read out this text.
> > 
> > 
> > Much simpler solution would be to just add text to the title file, because then you do not need to run the exact same pieces of code multiple times. And if there is no text, the returned value will be empty string which does not impact TTS whatsoever, so i believe the original solution would be more efficient (unless i'm missing something)
> 
> See my previous reply. I agree it would be simpler but it would also conflict with other parts that may need to use the title. e.g. #139
> 
> Additionally it may hit the character limit if we implement the new TTS api in #92

alright, fair enough, let me fix that

**Comment by MeDBeD1** [comment]
Just making an update: i did rewrite the code to fit the requirements, however, screenshots are fully broken on larger posts
title
i can either try to fix it and then push an update, or update it with the current state of things

**Comment by JasonLovesDoggo** [comment]
> Just making an update: i did rewrite the code to fit the requirements, however, screenshots are fully broken on larger posts title i will try to fix it for another pull request, on this one i will focus solely on TTS

why not just have multiple screenshots?

**Comment by MeDBeD1** [comment]
> > Just making an update: i did rewrite the code to fit the requirements, however, screenshots are fully broken on larger posts title i will try to fix it for another pull request, on this one i will focus solely on TTS
> 
> why not just have multiple screenshots?

that is exactly what i want to do, but i'm too tired to implement it now, i will finish off some testing with current pull request, and work on screenshots either for new one, or this one if it isn't closed by that time

**Review by CallumIO — COMMENTED** [review]
Looks great to me, I'll test on my end in the morning.
I take it you have tested this?

**Comment by jacesleeman** [comment]
ok so it doesnt work with #92 it uses the male for the title and it only shows the ss for the reading of the titile ill see if i can mess with it to get it to work with 92

**Comment by prasannakarki** [comment]
> ok so it doesnt work with #92 it uses the male for the title and it only shows the ss for the reading of the titile ill see if i can mess with it to get it to work with 92 plus it made a 3min vid aswell witch idk if thats good or not if we use pr92 we need to break up story clips into 550 words each

I think this depends on the subreddit. Like malicious compliance doesn't need to read comments just story. So for that 3 minutes would be fine. But for ask reddit 3 minutes sounds like torture. I think the current settings makes story long as the first comment and if it's longer than 50seconds it stops reading next one which is fine. There are other options for tts but idk if they are any good as 550 text seems like a huge limitation but if someone gets long stories divided into multiple screen shots it will work out.

**Comment by jacesleeman** [comment]
> > ok so it doesnt work with #92 it uses the male for the title and it only shows the ss for the reading of the titile ill see if i can mess with it to get it to work with 92 plus it made a 3min vid aswell witch idk if thats good or not if we use pr92 we need to break up story clips into 550 words each
> 
> I think this depends on the subreddit. Like malicious compliance doesn't need to read comments just story. So for that 3 minutes would be fine. But for ask reddit 3 minutes sounds like torture. I think the current settings makes story long as the first comment and if it's longer than 50seconds it stops reading next one which is fine. There are other options for tts but idk if they are any good as 550 text seems like a huge limitation but if someone gets long stories divided into multiple screen shots it will work out.

i use amitheasshole it read the story just didnt show the ss the whole time and yea pr 92 atm seems like the best bet but i have zero clue how to go about breaking up storys into 550 word files for it to work with it

**Comment by jacesleeman** [comment]
> > > ok so it doesnt work with #92 it uses the male for the title and it only shows the ss for the reading of the titile ill see if i can mess with it to get it to work with 92 plus it made a 3min vid aswell witch idk if thats good or not if we use pr92 we need to break up story clips into 550 words each
> > 
> > 
> > I think this depends on the subreddit. Like malicious compliance doesn't need to read comments just story. So for that 3 minutes would be fine. But for ask reddit 3 minutes sounds like torture. I think the current settings makes story long as the first comment and if it's longer than 50seconds it stops reading next one which is fine. There are other options for tts but idk if they are any good as 550 text seems like a huge limitation but if someone gets long stories divided into multiple screen shots it will work out.
> 
> i use amitheasshole it read the story just didnt show the ss the whole time and yea pr 92 atm seems like the best bet but i have zero clue how to go about breaking up storys into 550 word files for it to work with it

havent tested with #pr234 yet tho

**Comment by jacesleeman** [comment]
did u change something

**Comment by jacesleeman** [comment]
have u fixed it showing the sreen shot for only a few seconds while its reading yet

**Comment by MeDBeD1** [comment]
> have u fixed it showing the sreen shot for only a few seconds while its reading yet

as far as my tests showed, it's fixed now

**Review by CallumIO — APPROVED** [review]
All good, fixes other issues as discussed, thank you for this feature :D

**Comment by KingCaliph** [comment]
What happened to this feature? I'm still somewhat inexperienced with GIthub, but I thought a pull request being merged meant it was added to the primary file/download, yet this feature isn't available anymore it seems. Did it simply get removed from the newest version or is there something I'm missing?

**Comment by OpenSourceSimon** [comment]
> What happened to this feature? I'm still somewhat inexperienced with GIthub, but I thought a pull request being merged meant it was added to the primary file/download, yet this feature isn't available anymore it seems. Did it simply get removed from the newest version or is there something I'm missing?

This feature does exist, actually it's way better than this PR implementation. To enable this, set story_mode to True in the config.

**Comment by KingCaliph** [comment]
> > What happened to this feature? I'm still somewhat inexperienced with GIthub, but I thought a pull request being merged meant it was added to the primary file/download, yet this feature isn't available anymore it seems. Did it simply get removed from the newest version or is there something I'm missing?
> 
> This feature does exist, actually it's way better than this PR implementation. To enable this, set story_mode to True in the config.

Oh, perhaps I misunderstood the purpose of this PR. I thought the intent was to have both the text under the title read and the comments (e.g. the title and text below it would be read--giving context--then it would proceed to the comments to see responses. This seems especially useful for AITA and alike threads). I didn't realize the purpose was to only read the title and story that goes with it. Thanks for the clarification

**Pull request merged**
