### PR TITLE
Subscribe overlay to end of video

### PR DESCRIPTION
**Pull request by VirtualRabb**
Add subscribe overlay

# Description

I've created a subscribe overlay for the end of the videos.
It adds a overlay with a subscribe and hit the bell animation to the end of the video which can be seen in the video below

UPDATED LINK: https://youtube.com/shorts/6f6iomWNpaw?feature=share

New setting in config for enabling and disabling the overlay
If it's disabled from the start it will not download or create the folders required to use the overlay

-- Choose between multiple overlays
I've added a new setting within the config file, where you can choose between 
youtube, tiktok and instagram overlays!

-- Moved the add overlay method into the proper class
I've the thing that composites the overlay onto the video from the final_video.py to video.py

It uses google drive to store the file for download

# Checklist:

- [X] I am pushing changes to the **develop** branch
- [X] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have formatted and linted my code using python-black and pylint
- [X] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [X] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

Enable the sub_overlay in config or on startup.

### CODE REVIEW

**Comment by StopmotionSimonYT** [comment]
Awesome! But can you make that the user can select other clips easier? Because the videos can also be uploaded to TikTok and Instagram reels

**Comment by VirtualRabb** [comment]
> Awesome! But can you make that the user can select other clips easier? Because the videos can also be uploaded to TikTok and Instagram reels

Sounds like an great idea! I'll see if I can get that implemented!
Thank you the suggestion!

**Comment by JasonLovesDoggo** [comment]
> > Awesome! But can you make that the user can select other clips easier? Because the videos can also be uploaded to TikTok and Instagram reels
> 
> Sounds like an great idea! I'll see if I can get that implemented! Thank you the suggestion!

I will review once that is implemented

**Comment by StopmotionSimonYT** [comment]
Perfect! One little idea, maybe upload the files to this repository. Because the Google Drive links can be edited or removed. This is just a suggestion, you don't have to do it.

**Comment by JasonLovesDoggo** [comment]
> Perfect! One little idea, maybe upload the files to this repository. Because the Google Drive links can be edited or removed. This is just a suggestion, you don't have to do it.

@VirtualRabb I would 100% say to do this

**Comment by VirtualRabb** [comment]
> > Perfect! One little idea, maybe upload the files to this repository. Because the Google Drive links can be edited or removed. This is just a suggestion, you don't have to do it.
> 
> @VirtualRabb I would 100% say to do this

It says the files are to big.-.

**Comment by StopmotionSimonYT** [comment]
> It says the files are to big.-.
Did you upload with GitHub web or git? Git supports larger files

**Comment by VirtualRabb** [comment]
> > It says the files are to big.-.
> 
> Did you upload with GitHub web or git? Git supports larger files

Sorry for being so slow, had work this entire weekend. I've added them in through the github desktop. So now they should be in :d

**Comment by StopmotionSimonYT** [comment]
> > > It says the files are to big.-.
> > 
> > Did you upload with GitHub web or git? Git supports larger files
> 
> Sorry for being so slow, had work this entire weekend. I've added them in through the github desktop. So now they should be in :d

Awesome! But can you check why there are merge conflicts?

**Comment by VirtualRabb** [comment]
> > Sorry for being so slow, had work this entire weekend. I've added them in through the github desktop. So now they should be in :d
> 
> Awesome! But can you check why there are merge conflicts?

If i could figure that out i would, I've tried everything I know, kinda just wanna give up on that now can't find any conflicts so I dunno what to do now-.-

**Comment by StopmotionSimonYT** [comment]
> If i could figure that out i would, I've tried everything I know, kinda just wanna give up on that now can't find any conflicts so I dunno what to do now-.-

Don't give up, it's a good pull request! Do you have git? Then you can run the command `git status` and see what is the problem.

**Comment by StopmotionSimonYT** [comment]
If it's too hard to fix it (which I understand), you can always make a new branch and a new pull request.

**Comment by VirtualRabb** [comment]
> If it's too hard to fix it (which I understand), you can always make a new branch and a new pull request.

Yea I'll do that :d

**Pull request closed without merging**
