### PR TITLE
Add TTS for AWS Polly

### PR DESCRIPTION
**Pull request by llamojha**
This PR adds AWS Polly as TTS option adding a huge number of voices and languages to use. 
It will require having an AWS account and credentials with AWS Polly permissions. 

This follows the template from: https://github.com/elebumm/RedditVideoMakerBot/blob/feat/add-tts-generics/tts/example_tts.py

The code for TTS according to AWS is from their example here: https://docs.aws.amazon.com/polly/latest/dg/SynthesizeSpeechSamplePython.html

This is all the voices and languages available from AWS Polly: https://docs.aws.amazon.com/polly/latest/dg/voicelist.html 

Test video:

https://user-images.githubusercontent.com/8630545/172675714-7bf64350-5d35-4f69-bf0b-90ff59c0c524.mp4

### CODE REVIEW

**Review by CallumIO — APPROVED** [review]
Brilliant! Thank you very much :D

**Comment by ProjectSlxsh** [comment]
So I am running into this issue and I am not sure how to fix it

**Comment by ProjectSlxsh** [comment]
@llamojha

**Comment by ravsau** [comment]
I'm getting the following error when I run main.py in feat/add-tts-generics branch. Any tips on how to fix this error? ```[21:20:56] Getting video comments...                                                                                                                                                 subreddit.py:69
Received AskReddit threads successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Saving Text to MP3 files...                                                                                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/user/RedditPolly/RedditVideoMakerBot/main.py", line 91, in <module>
    length, number_of_comments = save_text_to_mp3(reddit_object)
  File "/Users/user/RedditPolly/RedditVideoMakerBot/video_creation/voices.py", line 41, in save_text_to_mp3
    return text_to_mp3.run()
  File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 50, in run
    self.call_tts("title", self.reddit_object["thread_title"])
  File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 93, in call_tts
    self.tts_module.run(text=text, filepath=f"{self.path}/{filename}.mp3")
AttributeError: 'str' object has no attribute 'run'

```

**Comment by llamojha** [comment]
> I'm getting the following error when I run main.py in feat/add-tts-generics branch. Any tips on how to fix this error? ```[21:20:56] Getting video comments... subreddit.py:69 Received AskReddit threads successfully. ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ Saving Text to MP3 files... │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ Traceback (most recent call last): File "/Users/user/RedditPolly/RedditVideoMakerBot/main.py", line 91, in length, number_of_comments = save_text_to_mp3(reddit_object) File "/Users/user/RedditPolly/RedditVideoMakerBot/video_creation/voices.py", line 41, in save_text_to_mp3 return text_to_mp3.run() File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 50, in run self.call_tts("title", self.reddit_object["thread_title"]) File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 93, in call_tts self.tts_module.run(text=text, filepath=f"{self.path}/{filename}.mp3") AttributeError: 'str' object has no attribute 'run'

Looks like it's complaining in the TTSProviders option. 

Can you provide more info? are you selecting the TTSProvider from the env or in the choice input?

**Comment by llamojha** [comment]
> > > So I am running into this issue and I am not sure how to fix it 
> > 
> > 
> > That last line is complaining about the profile name. I think your aws credentials are not set with the proper profile name.
> > The profile name used by this is set in here: https://github.com/elebumm/RedditVideoMakerBot/pull/432/files#diff-c273ddd3cc7a8d991b9dabf9104379265f5624d57c8890830ae6c51ad3e41dc4R9
> > so in your ~/.aws/credentials you should have your AWS secrets as:
> > ```
> > [polly]
> > aws_access_key_id=XXXXX
> > aws_secret_access_key=XXXXXX
> > ```
> 
> sorry didnt know it had to have a aws account till after i typed that message so sorry for bothering u

Don't worry. It's actually good feedback. I'll see if I can add it in the readme.

**Comment by ravsau** [comment]
> > I'm getting the following error when I run main.py in feat/add-tts-generics branch. Any tips on how to fix this error? ```[21:20:56] Getting video comments... subreddit.py:69 Received AskReddit threads successfully. ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ Saving Text to MP3 files... │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ Traceback (most recent call last): File "/Users/user/RedditPolly/RedditVideoMakerBot/main.py", line 91, in length, number_of_comments = save_text_to_mp3(reddit_object) File "/Users/user/RedditPolly/RedditVideoMakerBot/video_creation/voices.py", line 41, in save_text_to_mp3 return text_to_mp3.run() File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 50, in run self.call_tts("title", self.reddit_object["thread_title"]) File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 93, in call_tts self.tts_module.run(text=text, filepath=f"{self.path}/{filename}.mp3") AttributeError: 'str' object has no attribute 'run'
> 
> Looks like it's complaining in the TTSProviders option.
> 
> Can you provide more info? are you selecting the TTSProvider from the env or in the choice input?

I'm using env variables to set Polly as TTS provider. `TTS_PROVIDER="AWSPolly"`

I picked that up from one example in a PR. Is that the right way to do it?

**Comment by llamojha** [comment]
> > > I'm getting the following error when I run main.py in feat/add-tts-generics branch. Any tips on how to fix this error? ```[21:20:56] Getting video comments... subreddit.py:69 Received AskReddit threads successfully. ╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮ │ Saving Text to MP3 files... │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ Traceback (most recent call last): File "/Users/user/RedditPolly/RedditVideoMakerBot/main.py", line 91, in length, number_of_comments = save_text_to_mp3(reddit_object) File "/Users/user/RedditPolly/RedditVideoMakerBot/video_creation/voices.py", line 41, in save_text_to_mp3 return text_to_mp3.run() File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 50, in run self.call_tts("title", self.reddit_object["thread_title"]) File "/Users/user/RedditPolly/RedditVideoMakerBot/tts/engine_wrapper.py", line 93, in call_tts self.tts_module.run(text=text, filepath=f"{self.path}/{filename}.mp3") AttributeError: 'str' object has no attribute 'run'
> 
> > 
> 
> > Looks like it's complaining in the TTSProviders option.
> 
> > 
> 
> > Can you provide more info? are you selecting the TTSProvider from the env or in the choice input?
> 
> 
> 
> I'm using env variables to set Polly as TTS provider. `TTS_PROVIDER="AWSPolly"`
> 
> 
> 
> I picked that up from one example in a PR. Is that the right way to do it? 

Can you try without the env var and selecting it when the choice input happens? I'll check it too as soon as I can but it may take a couple of days as I'm on holidays

**Comment by llamojha** [comment]
> > Can you try without the env var and selecting it when the choice input happens? I'll check it too as soon as I can but it may take a couple of days as I'm on holidays
> 
> what do you mean by choice input? When I run `python main.py` the only input I'm asked for is the reddit thread link. Thanks for looking into this. No rush.

It's better if you use the latest from the main branch as it includes a version of 'polly': https://github.com/elebumm/RedditVideoMakerBot/blob/master/TTS/POLLY.py

**Pull request merged**
