### PR TITLE
Added pause between each comment

### PR DESCRIPTION
**Pull request by farev**
I was able to add a pause between each comment as I and several other people thought it would be a good improvement. I did it by adding an empty 1 second audio and a blank png to go with it, after every audio file. So after it read the comment it would pause for 1 second. Then I also made some changes in voices.py to adjust for the legth of the video with the added pauses.

### CODE REVIEW

**Comment by IslaFTW** [comment]
OMG @farev I've been asking for this improvement for days, where can I test your version? :D

**Comment by JasonLovesDoggo** [comment]
> OMG @farev I've been asking for this improvement for days, where can I test your version? :D 

Their fork

**Comment by JasonLovesDoggo** [comment]
Awesome work though

**Review by JasonLovesDoggo — CHANGES_REQUESTED** [review]
Please only add the delay and not other not only unneeded but unwanted changes

**Comment by lamasterso** [comment]
how can I download this version ? I visited @farev page but there is no fork there

**Comment by farev** [comment]
> how can I download this version ? I visited @farev page but there is no fork there

I will make the fork. I also think there probably is a better way to add a pause but what I did worked fine.

**Comment by IslaFTW** [comment]
> > how can I download this version ? I visited @farev page but there is no fork there
> 
> I will make the fork. I also think there probably is a better way to add a pause but what I did worked fine.

Download your version, but I don't see any variable to control the pause time, I don't see that it pauses, nor the transparent png, is there something that I don't configure correctly?

**Comment by CallumIO** [comment]
This PR doesnt use your code, please reopen with a pull from your fork to this repo's develop branch

**Pull request closed without merging**
