### PR TITLE
Environment Vars and Program Arguments

### PR DESCRIPTION
**Pull request by honzapatCZ**
# Description

This PR allows the use of environment vars and/or program arguments for populating the config in some sensitive areas.

None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

### CODE REVIEW

**Comment by OpenSourceSimon** [comment]
Why exactly is this needed? I think the config itself is safe enough and can be used much easier than modifying the command.

**Comment by honzapatCZ** [comment]
I am personally more inclined on the idea of running this in Docker.
But in general having secrets(especially passwords, or tokens) saved as part of some config is bad.
This way they can be supplied at actual runtime and in more advanced deployments(Github Actions for example) as repository secrets.

**Comment by OpenSourceSimon** [comment]
> I am personally more inclined on the idea of running this in Docker. But in general having secrets(especially passwords, or tokens) saved as part of some config is bad. This way they can be supplied at actual runtime and in more advanced deployments(Github Actions for example) as repository secrets.

That's actually a nice use case

**Comment by OpenSourceSimon** [comment]
Hey, I would love to merge this! But I'm a little bit confused by the code. Is it possible you can write some documentation on how to use it? Thanks in advance!

**Pull request closed without merging**
