### PR TITLE
better issues

### PR DESCRIPTION
**Pull request by hammamikhairi**
THIS IS THE SAME PR AS #1181 (switched to master branch)

# Description

This change should be a better alternative for the current default issues used in the repository issue tracker, done using this [github](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) feature.

it this change will : 
- help users submit better bug reports
- help users submit better Feature requests
- organize the repository issue tracker

# Issue Fixes
The [messy issue tracker](https://github.com/elebumm/RedditVideoMakerBot/issues) of the project repository.

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
   - [x] no need
- [ ] I have formatted and linted my code using python-black and pylint
   - [x] no need
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

i created a [test repository](https://github.com/hammamikhairi/better-issues/issues) where you can check the current issues (generated using this feature) and try creating an issue or a feature request

### CODE REVIEW

**Review by JasonLovesDoggo — APPROVED** [review]

**Comment by StopmotionSimonYT** [comment]
Can you add a check that the bug report is for the latest version? Because many people are using older versions. And the solution is to just update.

**Comment by hammamikhairi** [comment]
> Can you add a check that the bug report is for the latest version? Because many people are using older versions. And the solution is to just update.

there already is, in the system information section

**Comment by StopmotionSimonYT** [comment]
> > Can you add a check that the bug report is for the latest version? Because many people are using older versions. And the solution is to just update.
> 
> there already is, in the system information section

I mean adding a checkbox for the latest version. Now it asks which version you are using so you can use an older version

**Comment by hammamikhairi** [comment]
@JasonLovesDoggo can i commit the to the pr this change?

- only reporting bugs found in the latest version (they still can create normal issues, it will just make the maintainers' lives easier)

[an example](https://github.com/hammamikhairi/better-issues/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+)

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo can i commit the to the pr this change?
> 
> - only reporting bugs found in the latest version (they still can create normal issues, it will just make the maintainers' lives easier)
> 
> [an example](https://github.com/hammamikhairi/better-issues/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+)

We will still need the exact version string because we could have released a new version since that issue was created

**Comment by hammamikhairi** [comment]
> > @JasonLovesDoggo can i commit the to the pr this change?
> > 
> > * only reporting bugs found in the latest version (they still can create normal issues, it will just make the maintainers' lives easier)
> > 
> > [an example](https://github.com/hammamikhairi/better-issues/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+)
> 
> We will still need the exact version string because we could have released a new version since that issue was created

Understandable, the PR shall remain unchanged then.

**Pull request merged**
