### PR TITLE
Add community health files

### PR DESCRIPTION
**Pull request by CallumIO**
Adds
- Contributing Guidelines
- Pull Request Template

As discussed :D

### CODE REVIEW

**Review by jacesleeman — APPROVED** [review]

**Review by LukaHietala — APPROVED** [review]
All good.

**Review by LukaHietala — APPROVED** [review]
Good.

**Review by LukaHietala — APPROVED** [review]
Approved.

**Review by LukaHietala — APPROVED** [review]
👍.

**Pull request merged**
