### PR TITLE
added name_normalize to fix bugs with forbidden chars in videoname

### PR DESCRIPTION
**Pull request by Drugsosos**
Hey 👋🏻
There is some fixes for this issue with video's name

---
https://github.com/elebumm/RedditVideoMakerBot/issues/391

### CODE REVIEW

**Comment by CallumIO** [comment]
Correct me if I am wrong, but I believe forward slash ( / ) should also be filtered out, which doesnt seem to be done in your regex?

**Comment by Drugsosos** [comment]
> Correct me if I am wrong, but I believe forward slash ( / ) should also be filtered out, which doesnt seem to be done in your regex?

@CallumIO I think I understood you right and fixed it

**Comment by JasonLovesDoggo** [comment]
God I'm sorry I missed this but can you fix the merge conflicts and then I will merge this immediately

**Comment by Drugsosos** [comment]
@JasonLovesDoggo 

All done

**Comment by JasonLovesDoggo** [comment]
> @JasonLovesDoggo 
> 
> All done

Perfect a

**Pull request merged**
