### PR TITLE
translating threads feature

### PR DESCRIPTION
**Pull request by alperencantez**
Users can now specify their preferred language by entering the language's international code, the program will translate the texts and rewrite it using translator APIs. But if such language code doesn't exist the process will continue in English.

### CODE REVIEW

**Comment by micziz** [comment]
Did you add dependencies to requirements.py? If no, please add them.

**Comment by alperencantez** [comment]
> Did you add dependencies to requirements.py? If no, please add them.

I am using the first version of bot and it works perfect without installing 3rd parties but I realized that requirements.txt has gotten very smaller since the first release. So, I added my dependencies.

**Comment by micziz** [comment]
Also make shoure you are on the **LATEST** version, or you may encounter errors.

I was bugging about the requirements.txt beacause you may have them installed but the end user doesn't have them so instead of installing them one by one we install them all in one go.

**Comment by JasonLovesDoggo** [comment]
Please fix the merge conflicts before a merge can be done

**Pull request closed without merging**
