### PR TITLE
Fix merge conflicts in #280

### PR DESCRIPTION
**Pull request by HallowedDust5**
# Description

Title is self explanatory. I have not been able to do extensive bug testing, so it is more likely than not that there are some minor bugs that need fixing as this PR stands. I'm not in a good spot to determine whether the bugs I'm getting are from the code or the network I'm on, so I'm not going to try it. It would be much appreciated if someone else were to pick this up to fix those small bugs.

# Issue Fixes

Fixes merge conflicts found in PR #280 .

None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [ ] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [ ] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Please list the changes

**Comment by JasonLovesDoggo** [comment]
@CordlessCoder go hate on this

**Review by CordlessCoder — CHANGES_REQUESTED** [review]
Put SHEBANG lines back where they belong, actually document your code and changes you've made

**Comment by HallowedDust5** [comment]
I didnt do most of the changes, I said where those changes are listed.

**Comment by HallowedDust5** [comment]
And also, what are the shebang lines

**Comment by JasonLovesDoggo** [comment]
> And also, what are the shebang lines

Useful to other systems that definitely should not have been removed

**Comment by HallowedDust5** [comment]
I'm not trying to be rude, but that doesn't clear it up in the slightest for me.

**Comment by JasonLovesDoggo** [comment]
> I'm not trying to be rude, but that doesn't clear it up in the slightest for me.

And why doesn't need to. If you wanted to know you could Google it. All that matters is that they are important and they need to be kept.

**Comment by JasonLovesDoggo** [comment]
There are a load of changes in this that are both unwanted and uneeded

**Pull request closed without merging**
