### PR TITLE
async TTS api

### PR DESCRIPTION
**Pull request by Drugsosos**
Moved TTS to async api wherever it was possible

TODO:
---
* async api TTS
  - [x] move sync TTS requests to aiohttp
  - [ ] tests
* other fixes (duplicates from async webdriver)
  - [x] add pauses before/between TTS and pictures
  - [x] fix max_video_length (wasn't working correctly)
  - [x] fix for crop with vertical back videos

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
@Drugsosos you still working on this?

**Comment by Drugsosos** [comment]
> @Drugsosos you still working on this? 

@JasonLovesDoggo 
Kinda, I'm waiting for PR with async webdrivers
Then I'll close this PR and open new one so it'll be smaller

**Comment by JasonLovesDoggo** [comment]
> > @Drugsosos you still working on this? 
> 
> @JasonLovesDoggo 
> Kinda, I'm waiting for PR with async webdrivers
> Then I'll close this PR and open new one so it'll be smaller

Well I merged that one into a separate branch currently

**Comment by Drugsosos** [comment]
> > > @Drugsosos you still working on this?
> > 
> > 
> > @JasonLovesDoggo
> > Kinda, I'm waiting for PR with async webdrivers
> > Then I'll close this PR and open new one so it'll be smaller
> 
> Well I merged that one into a separate branch currently

@JasonLovesDoggo 
Oh, I missed a notification about that.
Will you merge it in develop or you wanna test it more?
If you wanna test it more is it ok if I open PR with async TTS there?

**Comment by JasonLovesDoggo** [comment]
> > > > @Drugsosos you still working on this?
> > > 
> > > 
> > > @JasonLovesDoggo
> > > Kinda, I'm waiting for PR with async webdrivers
> > > Then I'll close this PR and open new one so it'll be smaller
> > 
> > Well I merged that one into a separate branch currently
> 
> @JasonLovesDoggo 
> Oh, I missed a notification about that.
> Will you merge it in develop or you wanna test it more?
> If you wanna test it more is it ok if I open PR with async TTS there?

I'm going to test it and modify it a bit It's just a lot easier to do in a separate branch then an entire different fork.

**Comment by Drugsosos** [comment]
I'll open new PR when `New-WebDriver` will be merged in `develop` 
(it'll be way smaller cause there are lots of similar changes in both branches)

**Pull request closed without merging**
