### PR TITLE
Deleted Comments will no longer be used

### PR DESCRIPTION
**Pull request by null3000**
If there is no author the comment will not be grabbed. Will close:

- #222 
- #421

### CODE REVIEW

**Comment by mlvps** [comment]
_NameError: name 'comment' is not defined_

**Comment by null3000** [comment]
> > _NameError: name 'comment' is not defined_
> 
> can someone help me?

Fixed it with a new commit. Should work now.

**Comment by JasonLovesDoggo** [comment]
Seems good

**Comment by JasonLovesDoggo** [comment]
@null3000 fix the merge conflicts and then I will merge

**Comment by null3000** [comment]
@JasonLovesDoggo merge conflicts fixed.

**Pull request merged**
