### PR TITLE
Implement skipping pinned (FKA stickied) messages

### PR DESCRIPTION
**Pull request by sadmoonphoenix**
Adds an environment variable for config, and the code itself.

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
This won't work with the newest version of the checker that verq implemented

Also I don't see much of a reason why people would want stickied comments

**Review by JasonLovesDoggo — CHANGES_REQUESTED** [review]
See comment above

**Comment by sadmoonphoenix** [comment]
> This won't work with the newest version of the checker that verq implemented
> 
> Also I don't see much of a reason why people would want stickied comments

Is there a separate branch? I tried this with the develop branch (even merged to double check) and it seems to work fine.

**Comment by JasonLovesDoggo** [comment]
> > This won't work with the newest version of the checker that verq implemented
> > 
> > Also I don't see much of a reason why people would want stickied comments
> 
> Is there a separate branch? I tried this with the develop branch (even merged to double check) and it seems to work fine.

Could be verq hasn't pushed his changes yet

**Pull request closed without merging**
