### PR TITLE
Made ENV make more sense

### PR DESCRIPTION
**Pull request by Kamushy**
A couple were submitting links into the subreddit field

### CODE REVIEW

**Comment by reoccurcat** [comment]
> Also just curious, why does the .env.template need to be named that way why not just name it .env and save the end user a bit of time?

The `.env` is in the gitignore so it would get forgotten about by git, and even then if you removed that it would send your credentials into the repository. It just makes it a bit easier.

**Comment by alhassanv** [comment]
For the `subreddit` value, I read in another PR that `/r` wouldn’t work properly. Could anyone test this?

**Review by D3FUZED — CHANGES_REQUESTED** [review]
r/ does not always work properly, imo this is preferred: `# Enter a subreddit without r/, E.G. r/AskReddit would be AskReddit`

**Review by jacesleeman — APPROVED** [review]

**Review by D3FUZED — APPROVED** [review]

**Review by reoccurcat — APPROVED** [review]

**Review by CallumIO — APPROVED** [review]

**Comment by CallumIO** [comment]
Thank you!

**Pull request merged**
