### PR TITLE
Limits the length of video by number of seconds.

### LINKED ISSUE #379: [ FEATURE REQUEST ] Shorten videos to > 1 Minute
Shorten videos to > 1 Minute so they can be YouTube Shorts

### LINKED ISSUE #414: Video to long
Why are the videos longer then 60 seconds. Can I fix that?

### LINKED ISSUE #433: Making the videos ~1:43 long instead of maximum one minute

### PR DESCRIPTION
**Pull request by rougeplane**
Adds Feature:
- Limits the length of clip by number of seconds by changing  "max_length" and "min_length" variable in voices.py
- The video produced will be in range of whatever "max_length" and "min_length" are set to.
- The video will skip over the comments that exceed the max length while adding only those that don't.
- Please not sometimes video produced will be smaller than min length due to lack of comments.

Fixes #379
Fixed #414
Fixed #433

### CODE REVIEW

**Comment by rougeplane** [comment]
I tested it again by running the bot 8 times and always got a video less than 60 seconds  I also added a print line in my code and it 
prints as intended.

image

image

**Comment by gBlaku** [comment]
> I tested it again by running the bot 8 times and always got a video less than 60 seconds I also added a print line in my code and it prints as intended.
> 
> image
> 
> image

did you try it on any subreddit except Askreddit?

**Comment by rougeplane** [comment]
> did you try it on any subreddit except Askreddit? That's when it seems to act strange

I did run it on r/LifeProTip it worked perfectly tested it on r/tifu and it produced longer videos. The reason being the length of the postext.mp3 being longer than 1 min, It skipped comments. I have updated voices.py, Hopefully it works now.

**Comment by ZacJiang01** [comment]
What is yt_dlp and YoutubeDL?

**Comment by Cizzl** [comment]
Fixed #756

**Comment by LeNinjaHD** [comment]
> What is yt_dlp and YoutubeDL?

A YouTube Downloader

**Pull request closed without merging**
