### PR TITLE
Added new gameplay video options

### PR DESCRIPTION
**Pull request by whyisthesheep**
# Description

Added:
- minecraft-2
- multiversus
- fall-guys
- steep

as options for background gameplay

# Issue Fixes

None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

You can try setting the background video to
- minecraft-2
- multiversus
- fall-guys
- steep

### CODE REVIEW

**Review by OpenSourceSimon — APPROVED** [review]

**Comment by JasonLovesDoggo** [comment]
Do you have permission from the video creator?

**Comment by whyisthesheep** [comment]
> Do you have permission from the video creator?

Hi I have just checked over and replaced 2 of the videos and now all of the videos which I have commited are "free to use" (from video description on youtube)

**Review by OpenSourceSimon — CHANGES_REQUESTED** [review]
Thanks for your PR! Although, we switched to a `utils/backgrounds.json` file instead of CONSTANTS.py in the develop branch. Can you adapt the changes to that?

**Comment by whyisthesheep** [comment]
> Thanks for your PR! Although, we switched to a `utils/backgrounds.json` file instead of CONSTANTS.py in the develop branch. Can you adapt the changes to that?

Hi, my bad for not doing that it should be sorted now.

**Review by OpenSourceSimon — APPROVED** [review]
Looks good to me!

**Pull request merged**
