### PR TITLE
TikTok TTS is working again!

### PR DESCRIPTION
**Pull request by OpenSourceSimon**
# Description
Someone at https://github.com/oscie57/tiktok-voice made a PR for the working TikTok TTS. Max chars are limited to 200. Headers will work for now, same for the URL.

# Issue Fixes
A lot

# Checklist:

- [ ] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)
I'm not pushing to the develop branch because it is a huge fix. Many people have already tested it. But if we need to move it to the develop branch, that's fine.

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Only do one thing in one pr please, we don't want / need bug fixes, docs changes and other stuff in 1pr You can make multiple

**Comment by JasonLovesDoggo** [comment]
Why did you revert the changes made by Callum... Don't change his discriminator

**Comment by OpenSourceSimon** [comment]
> Why did you revert the changes made by Callum... Don't change his discriminator 

I only changed the TikTok TTS file

**Comment by OpenSourceSimon** [comment]
Closed because of #1252

**Pull request closed without merging**
