### PR TITLE
Adding prawcore to the requirements

### PR DESCRIPTION
**Pull request by NoFailer**
# Description

Multiple people on the discord ran into the issue that an error message would come up saying `ModuleNotFoundError: No module named 'prawcore'`. I was told `praw` itself is supposed to install it but apparently it does not? I cannot exactly verify if the people actually followed the steps correctly. Json told me to make a PR for it :) I took the value for the `requirements.txt` from [here](https://pypi.org/project/prawcore/). 

\- Adri

# Issue Fixes

 `ModuleNotFoundError: No module named 'prawcore'`

# Checklist:

- [ ] I am pushing changes to the **develop** branch
- [ ] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have formatted and linted my code using python-black and pylint
- [ ] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [ ] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

Go through the installation steps.

### CODE REVIEW

**Comment by NoFailer** [comment]
After discussing it with Json. Changed version to `2.3.0`.

**Comment by JasonLovesDoggo** [comment]
Please fix the merge conflicts

**Comment by NoFailer** [comment]
For some reason GitHub wants to merge 7 commits, 5 being from other people. No idea why it is doing that. Let me try to fix this.

**Comment by NoFailer** [comment]
I see what happened. The branch `patch-1` created by GitHub is based on the current main branch. You changing it to the development branch then created merge issues because of the changes in that dev branch that have not been merged to main yet.

**Review by OpenSourceSimon — APPROVED** [review]

**Pull request merged**
