### PR TITLE
Update .config.template.toml fix multiple subreddits regex

### LINKED ISSUE #1193: Incorrect input with correct subreddits formatting.

### PR DESCRIPTION
**Pull request by dasbts**
# Description
Minor change to the regex to allow multiple subreddits to be used. Previously, it would prompt the user even if multiple subreddits was entered successfully, and only after in the terminal/CMD if the user entered it again, it would work, for that run of main.py. This solves the issue as there was a missing part of the regex. 

# Issue Fixes
#1193 
#1020 
Probably more issues too, and we have discussed it in the Discord. 

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)
Change the [reddit.thread] config for "subreddit" in .config.template.toml from regex = "[_0-9a-zA-Z]+$" to regex = "[_0-9a-zA-Z\\+]+$"

### CODE REVIEW

**Review by OpenSourceSimon — APPROVED** [review]
Awesome! Looks good to me, @JasonLovesDoggo Can you review it too?

**Comment by JasonLovesDoggo** [comment]
Have you tested it?

**Comment by OpenSourceSimon** [comment]
> Have you tested it? @dasbts

I tested it in an online regex tester. It should work fine.

**Comment by gabx03** [comment]
For anyone that is getting problems on this, you gotta correct this like this: regex = "[_0-9a-zA-Z/+]+$" and not like this: regex = "[_0-9a-zA-Z\+]+$", because \, at least in windows is an escape key.

**Comment by OpenSourceSimon** [comment]
> For anyone that is getting problems on this, you gotta correct this like this: regex = "[_0-9a-zA-Z/+]+$" and not like this: regex = "[_0-9a-zA-Z\+]+$", because \, at least in windows is an escape key. 

A lot of people have this problem, can you tell more about this? And maybe open a pull request?

**Comment by gabx03** [comment]
Sure man. user @dasbts said that he corrected the line in .config.template.toml, in [reddit.thread] from regex = "[_0-9a-zA-Z]+$" to regex = "[_0-9a-zA-Z\+]+$", but this at least in windows does not work since the character '\' is an escape key, so you have to replace  '\' in this updated string regex = "[_0-9a-zA-Z\+]+$", with '/', like this:  regex = "[_0-9a-zA-Z/+]+$". It should work then.

**Comment by gabx03** [comment]
You gotta simply replace the string in [reddit.thread] for "subreddit" in .config.template.toml from regex = "[_0-9a-zA-Z]+$" to regex = "[_0-9a-zA-Z/+]+$", maybe I am clearer.

**Pull request merged**
