### PR TITLE
Fix multiple errors and improve code readability

### PR DESCRIPTION
**Pull request by Toretto99**
- Resolved 'StreamingData' error

- Fixed ffmpeg compatibility issues, particularly with M1 Macs

- Replaced pytube with yt-dl for better up-to-date functionality and M1 support

- Enhanced code readability and provided clear comments for beginners to understand the code easily

# Description

# Issue Fixes

None

# Checklist:

- [ ] I am pushing changes to the **develop** branch
- [ ] I am using the recommended development environment
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have formatted and linted my code using python-black and pylint
- [ ] I have cleaned up unnecessary files
- [ ] My changes generate no new warnings
- [ ] My changes follow the existing code-style
- [ ] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

### CODE REVIEW

**Comment by Zeedan345** [comment]
I've tried the code and it did take care of the errors mentioned above. Thanks!

**Comment by Toretto99** [comment]
I'm glad to hear that I was able to contribute to this project

**Comment by OpenSourceSimon** [comment]
Can you make this PR to the develop branch instead of master? yt-dlp is already implemented there so this will only add some comments

**Comment by Zeedan345** [comment]
Hey, I wanted to add something to my previous comment. Even though it fixes the errors, later on, I got some ffmpeg errors. I did try to find the cause, but couldn't. I solved all the issues by simply downloading the youtube video and then renaming it "bbswitzer-parkour.mp4" without changing any code.

**Pull request closed without merging**
