### PR TITLE
Add Dark Mode Option

### PR DESCRIPTION
**Pull request by arjun-dureja**
Dark mode can be enabled on Reddit by creating a cookie defining user preferences. This is stored as a Base64 encoded string. Opening Reddit in incognito and enabling dark mode results in these preferences:

`{"prefs":{"topContentDismissalTime":0,"globalTheme":"REDDIT","nightmode":true,"collapsedTraySections":{"favorites":false,"multis":false,"moderating":false,"subscriptions":false,"profiles":false},"topContentTimesDismissed":0}}
`

Change the `THEME` environment variable to "dark" to prompt the program to take screenshots in dark mode. 

Sample dark mode video (compressed due to GitHub limits):

https://user-images.githubusercontent.com/16995513/171478396-f5a451f8-39f0-4846-b3ca-f884bd2f9c9b.mp4

### CODE REVIEW

**Review by MartinAlcalde — APPROVED** [review]

**Review by JasonLovesDoggo — APPROVED** [review]
LGTM

**Comment by Kamushy** [comment]
Good idea

**Review by Kamushy — APPROVED** [review]

**Comment by mrawesomey** [comment]
> > Can you add the male voice and dark mode together pls would help a lot
> 
> It's a pr. if they want both they can merge both.

What is a pr. I am new so I#m sorry if I dont understand some stuff you say

**Comment by JasonLovesDoggo** [comment]
pr is a pull request and that's what this is.
merge means putting the suggested edits into the main codebase.

and well as to apply the changes to your code, you can either copy the code or use a .patch file but that is quite complex.
personally, for you, I would just recommend using my [fork](https://github.com/JasonLovesDoggo/RedditVideoMakerBot) as it has both dark mode, and a much better voice engine

(url https://github.com/JasonLovesDoggo/RedditVideoMakerBot)

**Comment by mrawesomey** [comment]
Thx I did some stuff and I joined both should I upload it?

**Review by ZENX0x2 — APPROVED** [review]
Looks good

**Review by CallumIO — APPROVED** [review]
LGTM.
Edited to allow any case of "dark" to be accepted

**Pull request merged**
