### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by UP929312**

### CODE REVIEW

**Review by NomsterDude — APPROVED** [review]
I don't see any problems here :)

**Review by NomsterDude — APPROVED** [review]
No problems here :)

**Review by FreebieII — CHANGES_REQUESTED** [review]
File is 2 weeks behind! Please update code to the latest in https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/final_video.py

**Comment by UP929312** [comment]
> Collaborator

It's 2 weeks behind because I wrote the PR 2 weeks ago?

**Comment by JasonLovesDoggo** [comment]
Implemented partially

**Pull request closed without merging**
