### PR TITLE
Including JasonLovesDoggo's massive branch into the main branch

### PR DESCRIPTION
**Pull request by elebumm**
Took the branch and made a seperate PR in order to not disrupt the existing codebase.

### CODE REVIEW

**Comment by LukaHietala** [comment]
Wow! 

This is a huge commit.

**Comment by JasonLovesDoggo** [comment]
> Wow!
> 
> This is a huge commit.

well its 100+ of my commits squashed into one

**Review by FreebieII — COMMENTED** [review]
Works for me.  Was able to create final video without any errors.

**Review by FreebieII — APPROVED** [review]
I was able to get `final_video.mp4`, first try.  I am happy with this PR 😊

**Pull request closed without merging**
