### PR TITLE
UX changes / Gives User More Info

### PR DESCRIPTION
**Pull request by null3000**
This PR gives the User more info about what the script is doing
1. It will tell the user more details about the thread (Upvotes, Number of Comments, Upvote Ratio)
2. tells user how many mp3 files there are and counts when each one is downloaded
3. tells user how many image files there are and counts when each one is downloaded
4. tells user how long video will be when video is being compiled
5. giant ASCII text logo when running `main.py`

### CODE REVIEW

**Comment by CallumIO** [comment]
Looks good to me - I'll test in the morning before merging!

**Review by CallumIO — APPROVED** [review]
Happy to merge this after conflicts are resolved! :D

**Comment by null3000** [comment]
> Happy to merge this after conflicts are resolved! :D

Done, no conflicts.

**Review by CallumIO — APPROVED** [review]

**Comment by CallumIO** [comment]
Great! Thank you very much!

**Pull request merged**
