### PR TITLE
Fixed Opacity Function

### LINKED ISSUE #1625: [Bug]: Opacity feature does not work and isn't implemented
### Describe the bug

I noticed there's an opacity setting, so I lowered it so people can see the video better and I noticed it didn't do anything. I searched through the code to see where opacity is referenced so I can fix it and I noticed the opacity setting isn't referenced anywhere. 

### Reproduction Steps

Set opacity to lower than 1, doesn't work

### Expected behavior

Lower the opacity.

### Screenshots

_No response_

### System Information

Operating System : MacOS Ventura
Python version : Python 3.10
App version / Branch : master (3.1)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by joshholly**
Fixed opacity so comments will have transparency if the user sets the "opacity" option below 1.
closes #1625 

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

### CODE REVIEW

**Review by OpenSourceSimon — APPROVED** [review]

**Review by joshholly — COMMENTED** [review]
int() wrapper shouldn't exist for the opacity setting.

**Comment by zgauhar** [comment]
I have tried to test it but doesn't seem to work. The opacity variable in final_video.py remains unused.

**Comment by joshholly** [comment]
That’s weird because when I set the aa= to a variable manually, it works.  So if you set it to 0.5 directly in the file, it’ll make all the screenshots transparent. Can anyone help me figure out how to get it to properly pull from the config file? Because I got opacity working. I just can’t get it to pull the opacity variable properly from the config file. Sent from my iPhoneOn May 28, 2023, at 5:06 AM, zgauhar ***@***.***> wrote:﻿
I have tried to test it but doesn't seem to work. The opacity variable in final_video.py remains unused.

**Comment by zgauhar** [comment]
Where is this aa= variable?

**Comment by OpenSourceSimon** [comment]
Works for me!

**Comment by zgauhar** [comment]
Never mind, while making manual changes to my repo, I missed 1 line.

**Pull request merged**
