### PR TITLE
Edited main.py and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Anvilator-web**
# Description
Added a line to code to the shutdown function to inform the user of exiting the program upon calling the function.
Currently, it only says "clearing temp files"

And,

Also wrote a section of CONTRIBUTING.md to help beginner developers to setup their fork of the repo as many beginners to github might not know how to setup this up.

As a beginner developer myself and as this is my first time contributing to someone else's repository,
I also faced the same problem of being unable to understand what to do first.
So, I wrote a small section in the Contributing guidelines to encourage more beginner developers to contribute to this repo.

# Issue Fixes

None

# Checklist:

- [✔️] I am pushing changes to the **develop** branch
- [✔️] I am using the recommended development environment
- [✔️ ] I have performed a self-review of my own code
- [✔️] I have commented my code, particularly in hard-to-understand areas
- [✔️] I have formatted and linted my code using python-black and pylint
- [✔️] I have cleaned up unnecessary files
- [✔️] My changes generate no new warnings
- [✔️] My changes follow the existing code-style
- [✔️] My changes are relevant to the project

# Any other information (e.g how to test the changes)

On pressing CTRL + C or any other event happening which calls the shutdown() function, the exiting message is shown 
and 
the contributing guidelines have been bettered a bit.

### CODE REVIEW

**Comment by LukaHietala** [comment]
Everything looks good to me. I approved the changes

**Comment by JasonLovesDoggo** [comment]
"Currently, it only says "clearing temp files"" 

Yeah. When you push Ctrl+C... That's when you know it will shut down anyways.

**Comment by JasonLovesDoggo** [comment]
And the command is python main.py not python3

**Comment by Anvilator-web** [comment]
> And the command is python main.py not python3

But I can run it with both lol

**Comment by Anvilator-web** [comment]
> "Currently, it only says "clearing temp files"" 
> 
> Yeah. When you push Ctrl+C... That's when you know it will shut down anyways. 
> 
> 

Sure

**Comment by JasonLovesDoggo** [comment]
> > And the command is python main.py not python3
> 
> But I can run it with both lol

Not always....

**Pull request merged**
