### PR TITLE
Added exe that runs main.py

### PR DESCRIPTION
**Pull request by XM9G**
# Description

Added RedditVideoMaker.exe which runs main.py so you don't have to do it manually,

### CODE REVIEW

**Comment by muhammedaksam** [comment]
It starts with a few errors.
`C:\Users\muham\Documents\GitHub\RedditVideoMakerBot>start "" "H:\PortableApps\RedditVideoMakerBot\results"`
System cannot find path specified. Access denied.

**Comment by CallumIO** [comment]
If you're going to add an executable, add the source instead and let the user build.

We will not add unverified executables to the code, that is dangerous.

**Comment by XM9G** [comment]
oops that something i was meant to remove but forgot

**Comment by JasonLovesDoggo** [comment]
This shows up as a virus so no.... Plus It's the exact same amount of work

**Pull request closed without merging**
