### PR TITLE
python version update to python 3.7

### PR DESCRIPTION
**Pull request by LevaniVashadze**
playwright needs python 3.7+ as seen here  https://playwright.dev/python/docs/intro#system-requirements
Getting started | Playwright Python

### CODE REVIEW

**Review by CordlessCoder — APPROVED** [review]
It's very hard to have a problem with this PR

**Comment by JasonLovesDoggo** [comment]
I think this is a great change It could use a bit of work on the formatting now

**Comment by LevaniVashadze** [comment]
Took a lot of time to write all the code for it

**Comment by JasonLovesDoggo** [comment]
> Took a lot of time to write all the code for it



You know for every one line of code it is written 40,000 lines of thought are processed

So really this is 40, 001 lines of code

**Pull request merged**
