### PR TITLE
Adds zoom function

### PR DESCRIPTION
**Pull request by liamb13**
# Description

Adds the ability to zoom in for screenshots. 

I found the text to be a little small in the videos, so I added the option to config a zoom level.

An example showing zoom levels 1 (default), 1.25 and 1.5:
image

# Issue Fixes

None

# Checklist:

- [X] I am pushing changes to the **develop** branch
- [X] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have formatted and linted my code using python-black and pylint
- [X] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [X] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)
* Haven't worked on GUI *
Could potentially use some rejigging to make the value make more sense. 
Although the current format aligns with the browser. My initial instinct was to use a value of 2, before realising 200% is really quite overkill:
image

### CODE REVIEW

**Comment by liamb13** [comment]
Any comments on this @OpenSourceSimon

**Comment by OpenSourceSimon** [comment]
> Any comments on this @OpenSourceSimon 

Have to test it

**Comment by crocogab** [comment]
it work well for me ty :)

**Comment by joshholly** [comment]
Hey. I had to revert back to the old screenshot_downloader.py because now it causes a timeout. Im not sure why.

**Comment by randomuser1090** [comment]
Bro, this is very cool. How can I add this to my bot? I'm new in coding

**Comment by liamb13** [comment]
> Hey. I had to revert back to the old screenshot_downloader.py because now it causes a timeout. Im not sure why.

@joshholly can you retest? I've just added the scroll_into_view_if_needed() function before it takes the screenshot.

I ran into the issue myself recently on only some posts - I turned headless off and noticed sometimes it wouldn't have the comment in view. It should now work as expected.

**Comment by liamb13** [comment]
> Bro, this is very cool. How can I add this to my bot? I'm new in coding

Take a look at: [Files Changed](https://github.com/elebumm/RedditVideoMakerBot/pull/1578/files) and copying the changes to your version

**Pull request merged**
