### PR TITLE
added profane filter in voices.py

### PR DESCRIPTION
**Pull request by Drugsosos**
Fix for issue https://github.com/elebumm/RedditVideoMakerBot/issues/407

I found good profane list, it'll do it's job. But I'm not sure what to replace it with, so half of the word will be replaced with * (or even more than half, if it's still offensive)

### CODE REVIEW

**Comment by Drugsosos** [comment]
@CallumIO 

I don't think there is one, I searched but found nothing decent on PyPI

**Comment by Niellles** [comment]
I found: https://github.com/snguyenthanh/better_profanity.

I especially like the whitelist which. However it doesn't seem to be recently updated, also there's some open issues (most concerning would be that the latest version is very slow).

**Comment by Drugsosos** [comment]
> I found: https://github.com/snguyenthanh/better_profanity.
> 
> I especially like the whitelist which would allow users to keep certain words without completely disabling the censoring. However it doesn't seem the package doesn't seem to be recently updated, also there's some open issues (most concerning would be that the latest version is very slow).
> 
> I do prefer @Drugsosos' way of censoring; only part of the word instead of the whole word.

Problem with other languages still remains. 
Only solution I see is to find profane lists in other languages.

**Review by kunderscore — APPROVED** [review]

**Comment by JasonLovesDoggo** [comment]
> > I found: https://github.com/snguyenthanh/better_profanity.
> > 
> > I especially like the whitelist which would allow users to keep certain words without completely disabling the censoring. However it doesn't seem the package doesn't seem to be recently updated, also there's some open issues (most concerning would be that the latest version is very slow).
> > 
> > I do prefer @Drugsosos' way of censoring; only part of the word instead of the whole word.
> 
> Problem with other languages still remains. 
> Only solution I see is to find profane lists in other languages.

Agree with this

Plus in my experience working with better profanity it really doesn't work well

**Pull request closed without merging**
