### PR TITLE
#1898 #1955 #1962 fix the Timeout during the screenshots, handle new login UI 

### PR DESCRIPTION
**Pull request by aliabusaleh**
# Description

I have update the screenshot issues of timeout + fixing the screenshot for the new Reddit UI

# Issue Fixes

#1898 
#1955 [Bug]: Timeout during the screenshots downloading

[Feature]: Update screenshots to beta layout #1954 
None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

### CODE REVIEW

**Comment by aliabusaleh** [comment]
hi @JasonLovesDoggo  can you check it, and merge if there are no problems?

**Comment by JasonLovesDoggo** [comment]
> hi @JasonLovesDoggo  can you check it, and merge if there are no problems? 

Can you have the other broader locators as a fallback?

**Comment by aliabusaleh** [comment]
> > hi @JasonLovesDoggo  can you check it, and merge if there are no problems?
> 
> Can you have the other broader locators as a fallback?

could you explain what you mean exactly? do you mean a fallback function?

**Comment by JasonLovesDoggo** [comment]
> > > hi @JasonLovesDoggo  can you check it, and merge if there are no problems?
> > 
> > Can you have the other broader locators as a fallback?
> 
> could you explain what you mean exactly? do you mean a fallback function? 

So when the select door you just added. Doesn't return a match, use the other one instead

**Comment by deadwyler69** [comment]
Now the screenshot is taken of the Reddit title and then the error appears

**Comment by aliabusaleh** [comment]
> > > > hi @JasonLovesDoggo  can you check it, and merge if there are no problems?
> > > 
> > > 
> > > Can you have the other broader locators as a fallback?
> > 
> > 
> > could you explain what you mean exactly? do you mean a fallback function?
> 
> So when the select door you just added. Doesn't return a match, use the other one instead

Got it, I handled it now and handled the issue in #1962 also for the new UI

**Comment by planted101** [comment]
Hey there! Great work :) Following up bc another bug came up and was wondering if have you faced this issue:

https://github.com/elebumm/RedditVideoMakerBot/issues/1962#issuecomment-1961859462

**Comment by aliabusaleh** [comment]
> Hey there! Great work :) Following up bc another bug came up and was wondering if have you faced this issue:
> 
> [#1962 (comment)](https://github.com/elebumm/RedditVideoMakerBot/issues/1962#issuecomment-1961859462)

I haven’t seen that error before from my side, but it’s clear say that the image you are trying to access doesn’t exist, please check your change with reload if crash happens, I believe the issue happened there then affected the other sequence of the code.

**Comment by 313hemant313** [comment]
Great work!

In this PR i can see we are getting the comment json body only and screenshot is of just the body not with author name and image.

Maybe if we can work something with below path (I could not solve this)
`page.locator('shreddit-comment').locator(f'[thingid="t1_{comment["comment_id"]}"]').scroll_into_view_if_needed()`

But i can see someone can solve this problem, i feel we can go to t1_comment_id and close below children comments and then take a screenshot.

**Comment by mikkoxs** [comment]
> Great work!
> 
> In this PR i can see we are getting the comment json body only and screenshot is of just the body not with author name and image.
> 
> Maybe if we can work something with below path (I could not solve this) `page.locator('shreddit-comment').locator(f'[thingid="t1_{comment["comment_id"]}"]').scroll_into_view_if_needed()`
> 
> But i can see someone can solve this problem, i feel we can go to t1_comment_id and close below children comments and then take a screenshot.
> 
> **UPDATE**
> 
> Able to get it work, with below code @aliabusaleh please review and if possible add in this PR ?
> 
> ```
> comment_meta_box = page.locator(f'shreddit-comment[thingid="t1_{comment["comment_id"]}"]').locator('summary').nth(0).bounding_box()
> page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").scroll_into_view_if_needed()
> # as zooming the body doesn't change the properties of the divs, we need to adjust for the zoom
> location = page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").bounding_box()
> location['x'] = comment_meta_box['x']
> location['y'] = comment_meta_box['y']
> location['height'] = comment_meta_box['height'] + location['height']
> location['width'] = max(comment_meta_box['width'], location['width'])
> ```
> 
> Also it would be great if you add below config in cookie-light-mode.json and cookie-dark-mode.json files.
> 
> ```
> Light:
> {
>     "name": "theme",
>     "value": "1",
>     "domain": ".reddit.com",
>     "path": "/"
>   }
>   
>   Dark:
>   {
>     "name": "theme",
>     "value": "2",
>     "domain": ".reddit.com",
>     "pa
> ```th": "/"
>   }
> ```

Where do we add this code into the program?

**Comment by 313hemant313** [comment]
> > Great work!
> > In this PR i can see we are getting the comment json body only and screenshot is of just the body not with author name and image.
> > Maybe if we can work something with below path (I could not solve this) `page.locator('shreddit-comment').locator(f'[thingid="t1_{comment["comment_id"]}"]').scroll_into_view_if_needed()`
> > But i can see someone can solve this problem, i feel we can go to t1_comment_id and close below children comments and then take a screenshot.
> > **UPDATE**
> > Able to get it work, with below code @aliabusaleh please review and if possible add in this PR ?
> > ```
> > comment_meta_box = page.locator(f'shreddit-comment[thingid="t1_{comment["comment_id"]}"]').locator('summary').nth(0).bounding_box()
> > page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").scroll_into_view_if_needed()
> > # as zooming the body doesn't change the properties of the divs, we need to adjust for the zoom
> > location = page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").bounding_box()
> > location['x'] = comment_meta_box['x']
> > location['y'] = comment_meta_box['y']
> > location['height'] = comment_meta_box['height'] + location['height']
> > location['width'] = max(comment_meta_box['width'], location['width'])
> > ```
> > Also it would be great if you add below config in cookie-light-mode.json and cookie-dark-mode.json files.
> > ```
> > Light:
> > {
> >     "name": "theme",
> >     "value": "1",
> >     "domain": ".reddit.com",
> >     "path": "/"
> >   }
> >   
> >   Dark:
> >   {
> >     "name": "theme",
> >     "value": "2",
> >     "domain": ".reddit.com",
> >     "pa
> > ```th": "/"
> >   }
> > ```
> 
> Where do we add this code into the program?

- Light and Dark json context needs to be added in cookie-light-mode.json and cookie-dark-mode.json files.
- For comment meta box adding a image for reference (Near line with code page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").scroll_into_view_if_needed())
Screenshot 2024-02-27 at 4 48 48 PM

**Comment by mikkoxs** [comment]
> > Great work!
> > In this PR i can see we are getting the comment json body only and screenshot is of just the body not with author name and image.
> > Maybe if we can work something with below path (I could not solve this) `page.locator('shreddit-comment').locator(f'[thingid="t1_{comment["comment_id"]}"]').scroll_into_view_if_needed()`
> > But i can see someone can solve this problem, i feel we can go to t1_comment_id and close below children comments and then take a screenshot.
> > **UPDATE**
> > Able to get it work, with below code @aliabusaleh please review and if possible add in this PR ?
> > ```
> > comment_meta_box = page.locator(f'shreddit-comment[thingid="t1_{comment["comment_id"]}"]').locator('summary').nth(0).bounding_box()
> > page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").scroll_into_view_if_needed()
> > # as zooming the body doesn't change the properties of the divs, we need to adjust for the zoom
> > location = page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").bounding_box()
> > location['x'] = comment_meta_box['x']
> > location['y'] = comment_meta_box['y']
> > location['height'] = comment_meta_box['height'] + location['height']
> > location['width'] = max(comment_meta_box['width'], location['width'])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also it would be great if you add below config in cookie-light-mode.json and cookie-dark-mode.json files.
> > ```
> > Light:
> > {
> >     "name": "theme",
> >     "value": "1",
> >     "domain": ".reddit.com",
> >     "path": "/"
> >   }
> >   
> >   Dark:
> >   {
> >     "name": "theme",
> >     "value": "2",
> >     "domain": ".reddit.com",
> >     "pa
> > ```th": "/"
> >   }
> > ```
> 
> Where do we add this code into the program?

Thanks very much!

However, yestereday, using your code, I had no issues but today I'm getting the 30000ms timeout error, is there a fix for this?
image

**Comment by 313hemant313** [comment]
@aliabusaleh Its working for me, maybe it is due to some subreddit ? 

Can you please share the subreddit config value for which it has failed ?

**Comment by mikkoxs** [comment]
> @aliabusaleh Its working for me, maybe it is due to some subreddit ?
> 
> Can you please share the subreddit config value for which it has failed ?
> 
> **UPDATE**
> 
> After adding below page reload line, it is working fine. @aliabusaleh please test.
> 
> ```
> 
> page.reload()
> 
> comment_meta_box = page.locator(f'shreddit-comment[thingid="t1_{comment["comment_id"]}"]').locator('summary').nth(0).bounding_box()
> page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").scroll_into_view_if_needed()
> # as zooming the body doesn't change the properties of the divs, we need to adjust for the zoom
> location = page.locator(f"#t1_{comment['comment_id']}-comment-rtjson-content").bounding_box()
> location['x'] = comment_meta_box['x']
> location['y'] = comment_meta_box['y']
> location['height'] = comment_meta_box['height'] + location['height']
> location['width'] = max(comment_meta_box['width'], location['width'])
> ```

After adding the page.reload() function, program is still timing out with the same error: 

``` ╭──────────────────────────────────────────────────────────────────────────────╮
│ Sorry, something went wrong with this version! Try again, and feel free to   │
│ report this issue at GitHub or the Discord community.                        │
│ Version: 3.2.1                                                               │
│ Error: Timeout 30000ms exceeded.                                             │
│ =========================== logs ===========================                 │
│ waiting for                                                                  │
│ locator("shreddit-comment[thingid=\"t1_ksjry45\"]").locator("summary").first │
│ ============================================================                 │
│ Config: {'allow_nsfw': False, 'theme': 'light', 'times_to_run': 10,          │
│ 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1,                    │
│ 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,    │
│ 'zoom': 1.6, 'background': {'background_video': 'minecraft',                 │
│ 'background_audio': 'lofi', 'background_audio_volume': 0.03,                 │
│ 'enable_extra_audio': False, 'background_thumbnail': True,                   │
│ 'background_thumbnail_font_family': 'arial',                                 │
│ 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color':     │
│ '255,255,255'}, 'tts': {'voice_choice': 'tiktok', 'random_voice': False,     │
│ 'elevenlabs_voice_name': 'Bella', 'elevenlabs_api_key': 'REDACTED',          │
│ 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew',           │
│ 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED', 'python_voice': │
│ '1', 'py_voice_num': '2', 'silence_duration': 0.3, 'no_emojis': False}}      │
╰──────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/mikko/Developer/RedditVideoMakerBot/main.py", line 133, in <module>
    raise err
  File "/Users/mikko/Developer/RedditVideoMakerBot/main.py", line 115, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/mikko/Developer/RedditVideoMakerBot/main.py", line 69, in run_many
    main()
  File "/Users/mikko/Developer/RedditVideoMakerBot/main.py", line 53, in main
    get_screenshots_of_reddit_posts(reddit_object, number_of_comments)
  File "/Users/mikko/Developer/RedditVideoMakerBot/video_creation/screenshot_downloader.py", line 252, in get_screenshots_of_reddit_posts
    comment_meta_box = page.locator(f'shreddit-comment[thingid="t1_{comment["comment_id"]}"]').locator('summary').nth(0).bounding_box()
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 15518, in bounding_box
    self._sync(self._impl_obj.bounding_box(timeout=timeout))
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 109, in _sync
    return task.result()
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 131, in bounding_box
    return await self._with_element(
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 115, in _with_element
    handle = await self.element_handle(timeout=timeout)
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 315, in element_handle
    handle = await self._frame.wait_for_selector(
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 322, in wait_for_selector
    await self._channel.send("waitForSelector", locals_to_params(locals()))
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
    return await cb()
  File "/Users/mikko/Developer/RedditVideoMakerBot/venv/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("shreddit-comment[thingid=\"t1_ksjry45\"]").locator("summary").first
============================================================

```

**Comment by 313hemant313** [comment]
> @aliabusaleh Its working for me, maybe it is due to some subreddit ?
> 
> Can you please share the subreddit config value for which it has failed ?
> 

Its working fine for me, please share the subreddit config value ?

**Comment by JasonLovesDoggo** [comment]
If people are having this work for them. Please ping me on discord. My username in the server is json.

**Comment by mikkoxs** [comment]
Fixed the issue.

I realised that the account I was using was somehow using the old UI, after creating a new account everything worked again.

**Comment by fakebhai** [comment]
just don't forget to change it back to headless true after testing is done

**Pull request closed without merging**
