### PR TITLE
Watermark changes

### LINKED ISSUE #1630: [Feature]: Hide Watermark
### Summary

Add a way to disable software watermark

### Is your feature request related to a problem?

If this feature get's implemented the quality if video's can increase

### Describe the solution you'd like

Add a choice to enable with true or disable with false the watermark showing

### Describe alternatives you've considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by liamb13**
# Description

Adds the option to customise or hide the watermark.

# Issue Fixes

#1630

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

Test with following config values:

### Displays background credit
```toml
background_watermark = true
background_watermark_text = ""
```

### Display custom watermark
```toml
background_watermark = true
background_watermark_text = "Reddit Video Maker Bot"
```

### Hides watermark
```toml
background_watermark = false
background_watermark_text = ""
```

### CODE REVIEW

**Comment by electro199** [comment]
@JasonLovesDoggo  should we add this ?

**Comment by OpenSourceSimon** [comment]
> @JasonLovesDoggo  should we add this ?
> 

Nope. Due to copyright we need to credit the author

**Comment by liamb13** [comment]
> > @JasonLovesDoggo  should we add this ?
> > 
> 
> Nope. Due to copyright we need to credit the author

Yeah I kind of thought this. Could maybe revisit if we add custom background support

**Comment by JasonLovesDoggo** [comment]
Exactly what Simon said.

**Pull request closed without merging**
