### PR TITLE
Change from gtts to pyttsx3 and added the option to chose gender of voice

### PR DESCRIPTION
**Pull request by The-Drobe**
Hello, I have updated voices.py to allow you to choose the gender of the voice. You can select the gender of the voice in .env.

### CODE REVIEW

**Comment by EmreTech** [comment]
Looks to be an exact duplicate of #234.

**Comment by vnvs1** [comment]
does not work for me it keep loading at saving text to audio

**Comment by vnvs1** [comment]
Screen Shot 2022-06-04 at 21 21 15

**Comment by The-Drobe** [comment]
> Screen Shot 2022-06-04 at 21 21 15
> 

Which operating system are you on?

**Comment by vnvs1** [comment]
I have macos

**Comment by The-Drobe** [comment]
> I have macos 

I do not own a Mac but for its use on Linux you will need to install these packages `espeak ffmpeg libespeak1` so maybe you need to install the Mac equivalent with brew

**Comment by The-Drobe** [comment]
> I have macos 

If I have the time I will spin up a macos VM on my proxmox cluster to test the code. It works fine on windows tho.

**Comment by jacesleeman** [comment]
> Looks to be an exact duplicate of #234.

not a exact just a worse version stream labs api is the best but we need to make it where if its past 550 it makes 2 clips not one

**Pull request closed without merging**
