### PR TITLE
overhaul of the functions and QoL improvements

### PR DESCRIPTION
**Pull request by reoccurcat**
Here's a list of what I fixed or added to the program:

- I changed the dependency of `Pytube` to `yt-dlp` as Pytube was giving me errors and generally not working for me at all
- I added support for Reddit two-factor authentication so that people with 2FA can login
- I removed emojis from printing as they don't usually render in the console
- Edited the gitignore so that the pycache doesn't get thrown in as well
- Minor edit to the TTS so that the accent isn't different in the title than the description 
- Edited the `requirements.txt` with the new packages and fixed the numpy version as no versions were found for the previous one

The pull request I'm going to open in Moviepy's repository should fix the issue of clipping the downloaded video.
I may make further changes to the requirements.txt with exact version numbers.

### CODE REVIEW

**Comment by BlockArchitech** [comment]
> Edited the gitignore so that the pycache doesn't get thrown in as well

this is also in #125

**Comment by reoccurcat** [comment]
My apologies, I'll remove that then

**Comment by elebumm** [comment]
Really great update. Needed to get rid of PyTube.

**Comment by reoccurcat** [comment]
Thank you!

**Pull request merged**
