### PR TITLE
Added pyttsx3 instead of gTTS, now has a male voice.

### PR DESCRIPTION
**Pull request by 5vl**
You can probably do more with this than me - I'm new to python. You can change your speach speed in the .env.
It's also a lot faster. There probably is some way to have a female voice as well, I just don't know python good enough for this.

### CODE REVIEW

**Comment by EmreTech** [comment]
Isn't this a duplicate of #92? Well at least the "now has a male voice" part is

**Comment by 5vl** [comment]
> Isn't this a duplicate of #92? Well at least the "now has a male voice" part is

As far as I can tell, a bit. This uses a different API that doesn't make any requests to the web, and it might be more reliable as it is offline. I haven't used python in a long time. I tried it, and compared to gTTS it's a lot faster. For me, it took like 0.5 seconds for pyttsx3 and ~3 seconds for gTTS.

**Comment by Whitewolf342** [comment]
Im getting this issue when using this version with the male voice and some of the other versions. Any solution?

image

**Comment by Rufluenza** [comment]
it does not work with the new update

**Pull request closed without merging**
