### PR TITLE
Bg audio

### PR DESCRIPTION
**Pull request by liamb13**
# Description
Adds background audio option

# Issue Fixes

 #1499

# Checklist:

- [X] I am pushing changes to the **develop** branch
- [X] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have formatted and linted my code using python-black and pylint
- [X] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [X] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

* Haven't worked on GUI *

### CODE REVIEW

**Comment by OpenSourceSimon** [comment]
Hey @liamb13, thank you so much for your PRs! But can you make them of the development branch and not the main? Thanks in advance!

**Comment by liamb13** [comment]
@OpenSourceSimon sure can. Did you want me to recreate them?

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon sure can. Did you want me to recreate them?

I would love that, but I understand if you can't because it can take some time. Also thanks for the many PRs, it includes a lot of features we want. But can you make sure the code in the PR corresponds with the title? For example: the ChatGPT PR also includes the zoom code

**Comment by liamb13** [comment]
@OpenSourceSimon 

> > @OpenSourceSimon sure can. Did you want me to recreate them?
> 
> I would love that, but I understand if you can't because it can take some time. Also thanks for the many PRs, it includes a lot of features we want. But can you make sure the code in the PR corresponds with the title? For example: the ChatGPT PR also includes the zoom code

No worries at all, will go through and fix my errors with submissions. Just confirming the two new ones are correct? Or should I be requesting into main?

**Comment by OpenSourceSimon** [comment]
> @OpenSourceSimon 
> 
> > > @OpenSourceSimon sure can. Did you want me to recreate them?
> > 
> > I would love that, but I understand if you can't because it can take some time. Also thanks for the many PRs, it includes a lot of features we want. But can you make sure the code in the PR corresponds with the title? For example: the ChatGPT PR also includes the zoom code
> 
> No worries at all, will go through and fix my errors with submissions. Just confirming the two new ones are correct? Or should I be requesting into main?

Perfect!

**Pull request closed without merging**
