### PR TITLE
3 bugfixes (2 for GUI, 1 for storymode)

### LINKED ISSUE #1823: [Feature]: I fixed the storymodemethod=1 issue with the final image not displaying
### Summary

Final image not displaying while final audio plays

### Is your feature request related to a problem?

Yes, right now, when you do storymethod=1, sometimes, if not all the time, the final text image doesn't get added to the video. I fixed the issue on my bot. I can't do a pull request, because I've made so many changes to mine that I don't want to add to a main fork. 

So I will just give my code. In your /video_creation/final_video.py file, replace this code block:

```
elif settings.config["settings"]["storymodemethod"] == 1:
            for i in track(range(0, number_of_clips + 1), "Collecting the image files..."):
                image_clips.append(
                    ffmpeg.input(f"assets/temp/{reddit_id}/png/img{i}.png")["v"].filter(
                        "scale", screenshot_width, -1
                    )
                )
                background_clip = background_clip.overlay(
                    image_clips[i],
                    enable=f"between(t,{current_time},{current_time + audio_clips_durations[i]})",
                    x="(main_w-overlay_w)/2",
                    y="(main_h-overlay_h)/2",
                )
                current_time += audio_clips_durations[i]
```
                
With

```
elif settings.config["settings"]["storymodemethod"] == 1:
            for i in track(range(0, number_of_clips + 1), "Collecting the image files..."):  
                image_clips.append(
                    ffmpeg.input(f"assets/temp/{reddit_id}/png/img{i}.png")["v"].filter(
                        "scale", screenshot_width, -1
                    )
                )
               
                background_clip = background_clip.overlay(
                image_clips[i],
                enable=f"between(t,{current_time},{current_time + audio_clips_durations[i]})",
                x="(main_w-overlay_w)/2",
                y="(main_h-overlay_h)/2",
                )
                current_time += audio_clips_durations[i]
                
            #Code to grab final image and add it to the video.    
            final_audio_duration = float(
            ffmpeg.probe(f"assets/temp/{reddit_id}/mp3/postaudio-{number_of_clips}.mp3")["format"]["duration"]
            )
            final_image = ffmpeg.input(f"assets/temp/{reddit_id}/png/img{number_of_clips}.png")["v"].filter(
            "scale", screenshot_width, -1
            )
            background_clip = background_clip.overlay(
            final_image,
            enable=f"between(t,{current_time},{current_time + final_audio_duration})",
            x="(main_w-overlay_w)/2",
            y="(main_h-overlay_h)/2",
            )
            current_time += final_audio_duration
```
            
I know it's a hacky solution, but I have tried everything else, and nothing worked except this. Basically, place the `#Code to grab final image and add it to the video. ` outside of the for loop. This basically grabs the final audio duration, grabs the final image, and then appends it to the video. Because for some odd reason, the final image doesn't get included in the original for loop. So the code that I adds the final image in after the loop. 

### Describe the solution you'd like

Implement my code in with a new version of the reddit video bot but make sure to give me credit. 

### Describe alternatives you've considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rajniszp**
# Description

1. `background_choice` was an invalid key and it caused the "Settings" page not to load. Simply changed to `background_video`.
2. Parsing the 'checks' JSON in the script included in settings.html caused an error: the backslashes (which were present in the "regex" from "subreddit" section) were not escaped by the jinja's tojson method (and underlying JSON.dumps method). Simple replace to properly escape backslashes for JS code.
3. Using story mode (with method = 1) the last text image was not added to the video. The title was not considered, so it ended 1 item too early. In addition, the audio clips durations list was missing an item - same thing, title not considered. It was raised in the issue #1823 ( https://github.com/elebumm/RedditVideoMakerBot/issues/1823 ) and the author even provides a fix, but admits it's a "hacky solution". This is a proper fix.

# Issue Fixes

#1823

None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

1. Start GUI, enter "Settings" page
2. Generate a video with storymode enabled and storymodemethod = 1

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Please resolve conflits

**Comment by rajniszp** [comment]
Resolved

**Comment by rajniszp** [comment]
Any chance to reopen? The code changes aren't huge

**Comment by JasonLovesDoggo** [comment]
Once somebody tests this I would be happy to merge.

**Comment by vaylor27** [comment]
replace all instances of `backgrounds.json` with `background_videos.json`

**Comment by rajniszp** [comment]
Replaced. Browsing, watching, adding and deleting backgrounds with web gui seems to be working

**Pull request closed without merging**
