### PR TITLE
Sanitize Title & Post TTS 

### LINKED ISSUE #273: Remove Special Characters from Audio
Reading characters like “ and ! is weird so I recommend formatting all special characters out of the gTTS

### PR DESCRIPTION
**Pull request by itsZECHS**
Since the tts also reads special characters such as quotation, exclamation marks etc, the text passed to tts needs to processed/sanitized first. This patch does exactly that, it removes all special characters and url links from the text before it's passed to tts.

[Regex101 Demo](https://regex101.com/r/g7Iypa/1)

Closes #273

### CODE REVIEW

**Review by CallumIO — APPROVED** [review]
Happy to merge this once the conflicts are resolved :)

**Comment by itsZECHS** [comment]
Ready for merge!

**Comment by ss5nathan** [comment]
Does not work, accidental console log

Traceback (most recent call last):
  File "main.py", line 123, in <module>
    final_video = make_final_video(number_of_comments)
  File "/video_creation/final_video.py", line 55, in make_final_video
    console.log(f"[bold green] Video Will Be: {int_total_length} Seconds Long")
NameError: name 'console' is not defined

**Comment by itsZECHS** [comment]
> Does not work, accidental console log
> 
> Traceback (most recent call last): File "main.py", line 123, in final_video = make_final_video(number_of_comments) File "/video_creation/final_video.py", line 55, in make_final_video console.log(f"[bold green] Video Will Be: {int_total_length} Seconds Long") NameError: name 'console' is not defined

Not related to this PR, no changes have been made in `/video_creation/final_video.py`

**Comment by M00nMission** [comment]
> > #332 is your answer!
> 
> doesn't work for some reason, end up getting a `POSTPROCESSING` error; tried deleting Docker container + image and building fresh, won't work
> 
> > URL: https://www.youtube.com/watch?v=iAVbLq1C6RA
> > ╭────────────────────────────────────────────────────────────────────────────────────────────────────╮
> > │ We need to download the background video. This may be fairly large but it's only done once per     │
> > │ background.                                                                                        │
> > ╰────────────────────────────────────────────────────────────────────────────────────────────────────╯
> > Downloading the background video... please be patient.
> > [youtube] iAVbLq1C6RA: Downloading webpage
> > [youtube] iAVbLq1C6RA: Downloading android player API JSON
> > [info] iAVbLq1C6RA: Downloading 1 format(s): 313+251
> > [download] Resuming download at byte 83955529
> > [download] Destination: assets/mp4/iAVbLq1C6RA.f313.webm
> > [download] 100% of 788.80MiB in 00:49
> > [download] Destination: assets/mp4/iAVbLq1C6RA.f251.webm
> > [download] 100% of 4.26MiB in 00:00
> > [Merger] Merging formats into "assets/mp4/iAVbLq1C6RA.mp4"
> > ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3204, in process_info
> > replace_info_dict(self.post_process(dl_filename, info_dict, files_to_move))
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3374, in post_process
> > info = self.run_all_pps('post_process', info, additional_pps=info.get('__postprocessors'))
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3361, in run_all_pps
> > info = self.run_pp(pp, info)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3340, in run_pp
> > files_to_delete, infodict = pp.run(infodict)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 25, in run
> > ret = func(self, info, *args, **kwargs)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/common.py", line 129, in wrapper
> > return func(self, info)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 827, in run
> > self.run_ffmpeg_multiple_files(info['__files_to_merge'], temp_filename, args)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 282, in run_ffmpeg_multiple_files
> > return self.real_run_ffmpeg(
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/postprocessor/ffmpeg.py", line 321, in real_run_ffmpeg
> > raise FFmpegPostProcessorError(stderr.split('\n')[-1])
> > yt_dlp.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #1:0 -> #0:1 (copy)
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "main.py", line 111, in 
> > vidpath = download_background(length)
> > File "/app/video_creation/background.py", line 52, in download_background
> > ydl.download(vidurl)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3254, in download
> > self.__download_wrapper(self.extract_info)(
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3230, in wrapper
> > res = func(*args, **kwargs)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1386, in extract_info
> > return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1395, in wrapper
> > return func(self, *args, **kwargs)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1479, in __extract_info
> > return self.process_ie_result(ie_result, download, extra_info)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 1535, in process_ie_result
> > ie_result = self.process_video_result(ie_result, download=download)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 2640, in process_video_result
> > self.process_info(new_info)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 3206, in process_info
> > self.report_error('Postprocessing: %s' % str(err))
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 936, in report_error
> > self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
> > File "/usr/local/lib/python3.8/dist-packages/yt_dlp/YoutubeDL.py", line 879, in trouble
> > raise DownloadError(message, exc_info)
> 
> > yt_dlp.utils.DownloadError: ERROR: Postprocessing:   Stream #1:0 -> #0:1 (copy)

**Comment by itsZECHS** [comment]
Again not related to this PR.

@M00nMission please create a separate issue.

**Comment by itsZECHS** [comment]
45531df82316e186933f1eaad43952fe4260c8f8

Seems this PR has been already merged (in a way)

**Pull request closed without merging**
