### PR TITLE
Allow the user to set opacity for the screenshots

### PR DESCRIPTION
**Pull request by jacesleeman**
Might add it where the title and comments are different

### CODE REVIEW

**Comment by LukaHietala** [comment]
Looks good! The review will be added soon.

**Comment by jacesleeman** [comment]
> Looks good! The review will be added soon.

Should I add the titleopacity and comment opacity or keep it all the same

**Review by FreebieII — APPROVED** [review]

**Comment by alhassanv** [comment]
> > Looks good! The review will be added soon.
> 
> Should I add the titleopacity and comment opacity or keep it all the same

All should be the same tbh

**Review by CallumIO — CHANGES_REQUESTED** [review]
Looks good but to make it more robust could you make the following changes in `main.py`

- Line 11
```python
REQUIRED_VALUES = ["REDDIT_CLIENT_ID","REDDIT_CLIENT_SECRET","REDDIT_USERNAME","REDDIT_PASSWORD", "OPACITY"]
```

- Insert at line 32
```python
try:
    float(os.getenv("OPACITY"))
except:
    print(f"Please ensure that OPACITY is set between 0 and 1 in your .env file")
    configured = False
```

Would do it myself but not at PC.

Thanks

**Comment by jacesleeman** [comment]
> Looks good but to make it more robust could you make the following changes in `main.py`
> 
> * Line 11
> 
> ```python
> REQUIRED_VALUES = ["REDDIT_CLIENT_ID","REDDIT_CLIENT_SECRET","REDDIT_USERNAME","REDDIT_PASSWORD", "OPACITY"]
> ```
> 
> * Insert at line 32
> 
> ```python
> try:
>     float(os.getenv("OPACITY"))
> except:
>     print(f"Please ensure that OPACITY is set between 0 and 1 in your .env file")
>     configured = False
> ```
> 
> Would do it myself but not at PC.
> 
> Thanks

done

**Review by CallumIO — APPROVED** [review]
LGTM

Thanks for this

**Pull request merged**
