### PR TITLE
Complete fix of #1194

### PR DESCRIPTION
**Pull request by StopmotionSimonYT**
# Description
The working code for #1194. There were merge conflicts in that PR, so this is the fix. That PR DOESN'T need to be merged since the files are added to this PR too.

# Issue Fixes

Merge conflicts

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

### CODE REVIEW

**Comment by StopmotionSimonYT** [comment]
Hi @JasonLovesDoggo and @callumio,
I managed to add the videos to this PR, so only this needs to be merged. Can it be merged?

**Comment by VirtualRabb** [comment]
> Hi @JasonLovesDoggo and @callumio, I managed to add the videos to this PR, so only this needs to be merged. Can it be merged?

It's beautiful :D

**Comment by JasonLovesDoggo** [comment]
Please move them to a folder in the utils folder NOT in the assets folder that specifically designed to be bot generated

**Comment by StopmotionSimonYT** [comment]
> Please move them to a folder in the utils folder NOT in the assets folder that is specifically designed to be bot-generated
Done!

**Comment by callumio** [comment]
If you could reword you commits to be more descriptive, then force push, thatd be great. Other than that, can't look through it right now but a brief skim looks good.

**Comment by StopmotionSimonYT** [comment]
> If you could reword your commits to be more descriptive, then force push, thatd be great. Other than that, can't look through it right now but a brief skim looks good.

Hi, that's a good suggestion. But I'm new to git and only know the basics. How can I do that?

**Comment by JasonLovesDoggo** [comment]
> > If you could reword your commits to be more descriptive, then force push, thatd be great. Other than that, can't look through it right now but a brief skim looks good.
> 
> Hi, that's a good suggestion. But I'm new to git and only know the basics. How can I do that?

https://stackoverflow.com/questions/5509543/how-do-i-properly-force-a-git-push

**Comment by JasonLovesDoggo** [comment]
@StopmotionSimonYT still waiting on this fix

**Comment by StopmotionSimonYT** [comment]
> @StopmotionSimonYT still waiting on this fix

I tried it but it doesn't work. I will make a new pull request with one commit

**Pull request closed without merging**
