### PR TITLE
FFMPEG audio concatenation on develop branch + minor fixes

### PR DESCRIPTION
**Pull request by tonywiththetommy**
replaces moviepy audio concatenation with ffmpeg, removing audio clicks and pops

creates a list of clips to merge, then merges them

added silence to end of audio clips, uses user defined variable in config. **needs to be implemented into config generator**

added comment sorting, hot or top comments, uses user defined variable in config. **needs to be implemented into config generator**

changed max length TTS of TikTok, reduced to 270 as 300 was causing errors, not completing the mp3 

fixed incorrect spelling of default max length 

added filter to ignore threads with 0 comments

### CODE REVIEW

**Comment by JasonLovesDoggo** [comment]
Moviepy uses FFmpeg

**Comment by tonywiththetommy** [comment]
> Moviepy uses FFmpeg

this method produces far less audio glitches, clicks and pops etc. I can upload a comparison

**Comment by JasonLovesDoggo** [comment]
> > Moviepy uses FFmpeg
> 
> this method produces far less audio glitches, clicks and pops etc. I can upload a comparison
> 
> 
> 
> 

Please do

**Comment by tonywiththetommy** [comment]
> > > Moviepy uses FFmpeg
> > 
> > 
> > this method produces far less audio glitches, clicks and pops etc. I can upload a comparison
> 
> Please do
https://youtu.be/Wb3pkdWjB-4

**Comment by JasonLovesDoggo** [comment]
Revert videos.json

**Pull request closed without merging**
