### PR TITLE
setup.py refactored, added shebang lines and formatted files with python-black

### PR DESCRIPTION
**Pull request by CordlessCoder**
These changes mainly improve user experience and add the missing user input handling

### CODE REVIEW

**Review by FreebieII — APPROVED** [review]
I am happy with all changes / enhancements thus far.  

Most changes just improved quality of code as well as unneeded lines/functions.

**Comment by iaacornus** [comment]
why shebang? windows doesn't suppport them.

**Review by CallumIO — APPROVED** [review]
Thanks for this, great work :D

**Comment by BlockArchitech** [comment]
Thank you so much for this! In my original pr with the amount of inputs I knew we needed an input handler.

It definitely wasn't the best way to do things, either. Thanks @CordlessCoder, very cool.

**Pull request merged**
