### PR TITLE
Fixed TikTok voice with external API

### PR DESCRIPTION
**Pull request by zxcvbinz**
# Description

Fixed TikTok voice, changed API link, without session_id

# Issue Fixes

TikTok TTS API

None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

### CODE REVIEW

**Review by farukumarx64 — APPROVED** [review]
I tried this fix and it works

**Comment by OpenSourceSimon** [comment]
Good PR, although I don't know if we want to rely on an external service. Is that open source or self hosted?

**Comment by zxcvbinz** [comment]
It is an excellent solution in case of endpoint url change, without changing the bot code. The repo is public, is an open source project. 
https://github.com/Weilbyte/tiktok-tts

**Comment by OpenSourceSimon** [comment]
> It is an excellent solution in case of endpoint url change, without changing the bot code. The repo is public, is an open source project. 
> https://github.com/Weilbyte/tiktok-tts

The real source (/api) isn't open source. I'm afraid this isn't going to work out because I don't want this whole project relying on one random API.

**Pull request closed without merging**
