### PR TITLE
feat: tiktok sessionId (necessary for TikTok TTS to work) can be specified in the config.toml

### PR DESCRIPTION
**Pull request by jcolladosp**
# Description

Based on PR #1240 by @OpenSourceSimon and changes on the [tiktok-voice](https://github.com/oscie57/tiktok-voice) project, now TikTok TTS API needs a header cookie called `sessionid`.
I added the possibility to pass this cookie value from the GUI or add it int he config.toml

The value for the sessionid parameter can be obtained by logging on the TikTok web version and using the browser inspector, you just need to go to the cookies section:

image

# Issue Fixes

TikTok TTS API

# Checklist:

- [X] I am pushing changes to the **develop** branch
- [X] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have formatted and linted my code using python-black and pylint
- [X] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [X] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

### CODE REVIEW

**Comment by OpenSourceSimon** [comment]
Thanks for the effort you put in this PR! But this needs to be good documented. Because it's hard for a user to get that session ID. I think we can't ask the user for it because it's not user-friendly.

**Comment by jcolladosp** [comment]
Hi, I agree with that. That's why the parameter is optional and I added this in the description: Check documentation if you don't know how to obtain it.

I dont know how to make a PR for the docs website, sorry.

**Comment by OpenSourceSimon** [comment]
I made a beginning of the documentation for this part, but it's not very detailed. You can view it [here](https://github.com/LewisProjects/RedditVideoMakerBot-website/pull/9)

**Comment by OpenSourceSimon** [comment]
@jcolladosp Could you add a check if the value session id exists in TikTok.py?

**Comment by jcolladosp** [comment]
> @jcolladosp Could you add a check if the value session id exists in TikTok.py?

Hi, I will try to do it today. Thanks for your contribution on documentation.

**Comment by OpenSourceSimon** [comment]
> > @jcolladosp Could you add a check if the value session id exists in TikTok.py?
> 
> Hi, I will try to do it today. Thanks for your contribution on documentation.

Any updates?

**Comment by jotonedev** [comment]
I think, in the future, the URL will need to be changed as they have multiple endpoints for this api.

**Comment by OpenSourceSimon** [comment]
> I think, in the future, the URL will need to be changed as they have multiple endpoints for this api.

I also think that. Maybe we can put a JSON file on a server (the docs server for example) where the URLs are stored. Then the bot can pick a random one. If TikTok changes the URL, then the user doesn't needs to update.

**Comment by jotonedev** [comment]
> > I think, in the future, the URL will need to be changed as they have multiple endpoints for this api.
> 
> I also think that. Maybe we can put a JSON file on a server (the docs server for example) where the URLs are stored. Then the bot can pick a random one. If TikTok changes the URL, then the user doesn't needs to update.

Yeah, it could work.

Also, I have done my version of the implementation of the sessionid with various improvements, before seeing this pull request. Is there a way I can contribute with my code to this pull request?

**Comment by OpenSourceSimon** [comment]
> > > I think, in the future, the URL will need to be changed as they have multiple endpoints for this api.
> > 
> > I also think that. Maybe we can put a JSON file on a server (the docs server for example) where the URLs are stored. Then the bot can pick a random one. If TikTok changes the URL, then the user doesn't needs to update.
> 
> Yeah, it could work.
> 
> Also, I have done my version of the implementation of the sessionid with various improvements, before seeing this pull request. Is there a way I can contribute with my code to this pull request?

That isn't possible, but feel free to create a new pull request!

**Comment by OpenSourceSimon** [comment]
Thanks for your work! But @jotonedev made a better version

**Pull request closed without merging**
